name: Build and Lint

on:
  pull_request:
    branches: [main]
    paths:
      - 'fusian-web/**'
      - '.github/workflows/build.yml'
  workflow_call:
    inputs:
      static_export:
        description: 'Build for static export (GitHub Pages)'
        required: false
        default: false
        type: boolean

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./fusian-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: fusian-web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Configure Next.js for static export
        if: ${{ inputs.static_export }}
        run: |
          cat > next.config.ts << 'EOF'
          import type { NextConfig } from "next";

          const nextConfig: NextConfig = {
            output: 'export',
            trailingSlash: true,
            images: {
              unoptimized: true
            },
            basePath: process.env.NODE_ENV === 'production' ? '/fusian' : '',
            assetPrefix: process.env.NODE_ENV === 'production' ? '/fusian' : '',
          };

          export default nextConfig;
          EOF

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload build artifacts (standard build)
        if: ${{ !inputs.static_export }}
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: fusian-web/.next/
          retention-days: 1

      - name: Upload build artifacts (static export)
        if: ${{ inputs.static_export }}
        uses: actions/upload-artifact@v4
        with:
          name: static-export
          path: fusian-web/out/
          retention-days: 1
